version: "3"
services:
  database:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_DATABASE: database01
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8001:80
    depends_on:
      - database
  
  wordpress:
    image: wordpress:latest
    volumes:
      - ./wordpress/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: database01
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    
    depends_on:
      - database